server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include:  ["health","info","shutdown", "refresh", "bus-refresh"]
spring:
  rabbitmq:
    port: 5672
    host: hebidu.cn
    password: 136799711
    username: hebidu
    virtual-host: /