server:
  port: 6004
spring:
  application:
    name: microservice-bookstore
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 136799711
    url: jdbc:mysql://pmd.local.hebidu.cn:3306/bookstore
#    username: hebidu
 #   password: 364945361
  #  url: jdbc:mysql://qqav.club:3306/bookstore
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
 #     ddl-auto: none
#    show-sql: false
#    generate-ddl: false
    open-in-view: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-single.hebidu.cn:8002/eureka/

management:
  endpoints:
    web:
      exposure:
        include: ["health", "info"]
