server:
  port: 8084
eureka:
  client:
    service-url:
      defaultZone: http://eureka-single.hebidu.cn:8002/eureka/
    fetch-registry: true
spring:
  application:
    name: microservice-producer-hello

