server:
  port: 8004
spring:
  application:
    name: microservice-bookstore
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: hebidu
    password: 364945361
    url: jdbc:mysql://qqav.club:3306/bookstore
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
      ddl-auto: update
    show-sql: true
    generate-ddl: false
eureka:
  client:
    service-url:
      default-zone: http://eureka-single.hebidu.cn:8002/eureka/
