spring:
  application:
    name: eureka-single-server
  profiles:
    active: default
server:
  port: 8002

eureka:
  instance:
    hostname: eureka-single.hebidu.cn
    #eureka-single.hebidu.cn
    instance-id: eureka-single:${spring.application.name}:${spring.application.instance_id:${server.port}}
    #environment: test
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
