spring:
  application:
    name: eureka-single-server
server:
  port: 8002
eureka:
  instance:
    hostname: eureka-single.hebidu.cn
    instance-id: eureka-single:${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    service-url:
      registerWithEureka: false
      fetchRegistry: false
      defaultZone: http://eureka-single.hebidu.cn:8002/eureka/