---
server:
  port: 8002
spring:
  profiles: eureka-peer1.hebidu.cn
eureka:
  instance:
    hostname: eureka-peer1.hebidu.cn
  client:
    serviceUrl:
      defaultZone: http://eureka-peer2.hebidu.cn:8003/eureka/

---
server:
  port: 8003
spring:
  profiles: eureka-peer2.hebidu.cn
eureka:
  instance:
    hostname: eureka-peer2.hebidu.cn
  client:
    serviceUrl:
      defaultZone: http://eureka-peer1.hebidu.cn:8002/eureka/