server:
  port: 8086
eureka:
  client:
    service-url:
      defaultZone: http://eureka-single.hebidu.cn:8002/eureka/
    register-with-eureka: true
spring:
  application:
    name: microservice-consumer-hello
