server:
  port: 8001
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/h136799711/spring-cloud-test.git
          search-paths: config-server/config-repo
        overrides:
          copyright: hebidu
  profiles:
    active: default

  rabbitmq:
    host: localhost
    port: 8004
    username: springcloud
    password: 136799711

management:
  endpoints:
    web:
      exposure:
        include:  ["health","info","shutdown", "refresh", "bus-refresh"]

