server:
  port: 8001
spring:
  application:
    name: spring-cloud-config-server

  cloud:
    config:
      server:
        git:
          #uri: https://github.com/h136799711/spring-cloud-test.git
          #search-paths: config-server/config-repo
          uri: /Users/git/spring-cloud-test/