server:
  port: 8001
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/h136799711/spring-cloud-test.git
          search-paths: config-server/config-repo
        overrides:
          copyright: hebidu
  profiles:
    active: default
  rabbitmq:
    port: 5672
    host: 127.0.0.1
    password: 136799711
    username: guest


management:
  endpoints:
    web:
      exposure:
        include:  ["health","info","shutdown", "refresh", "bus-refresh"]
